### ISSUE TITLE
Прыгают все шарики

### ISSUE THREAD

**Issue by marusama** [Newbilius/ColorLinesUnity#3]
Видео:
[Запись экрана 2018-12-05 23:45:11.zip](https://github.com/Newbilius/ColorLinesUnity/files/2650594/2018-12-05.23.45.11.zip)
Достаточно нажать три раза на шарик (тройной клик)
Firefox, ubuntu

**Comment by Newbilius** [comment]
Ахаха, вот это да! :-D Спасибо, попробую исправить. Воспроизводится во всех версиях, включая мобильную.
